url: "https://ydbata.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Y's site" # the name of your site, e.g. ACME Corp.
sass:
  load_paths:
    - _sass
    - node_modules
deploy:
  type: git
  repo: https://github.com/YDbata/YDbata.github.io
  branch: master